name: CI para C

on:
  push:

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compilar o programa
      run: gcc Github.com -o programa

    - name: Executar o programa
      run: ./programa

    - name: Executar testes automatizados
      run:
          gcc -o teste teste.c
          ./teste
      
     
